# Render Deployment Configuration
service:
  name: spa-vip-pipeline
  env: python
  region: oregon
  plan: standard
  
  buildCommand: chmod +x build.sh && ./build.sh
  startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
  
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.7
    - key: SUPABASE_URL
      sync: false  # Set manually in dashboard
    - key: SUPABASE_KEY  
      sync: false  # Set manually in dashboard
